schema:
  format:
    openapi: "3.0.0"
  service_input_type: "BackendFargateServiceInput"

  types:
    BackendFargateServiceInput:
      type: object
      description: "Input properties for a Backend Fargate service"
      properties:
        port:
          title: "Port"
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        desired_count:
          title: "Desired count"
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          title: "Task size"
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        subnet_type:
          title: "Subnet Type"
          type: string
          description: "Subnet type for your service"
          enum: ["public", "private"]
          default: "public"
        image:
          title: "Image"
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/nginx/nginx:1.21"
          minLength: 1
          maxLength: 200
